In [3]:
# ==========================================
# IMPORT LIBRARIES
# ==========================================

import pandas as pd
import numpy as np

print("="*60)
print("LIBRARIES IMPORTED SUCCESSFULLY")
print("="*60)

============================================================
LIBRARIES IMPORTED SUCCESSFULLY
============================================================

In [5]:
# ==========================================
# CREATE SAMPLE DATASET
# ==========================================

data = {
    "ID":[101,102,103,104,105,105,106,107,108,109],
    "Name":["Amit","Rahul","Priya","Sneha","Amit","Amit","Neha",None,"Karan","Riya"],
    "Age":[20,21,np.nan,22,20,20,23,21,np.nan,24],
    "City":["Ahmedabad","Surat","Rajkot","Ahmedabad","Ahmedabad","Ahmedabad","Vadodara","Rajkot","Surat",None],
    "Marks":[80,90,np.nan,75,80,80,95,88,92,90]
}

df = pd.DataFrame(data)

print("="*60)
print("ORIGINAL DATASET")
print("="*60)

display(df)

============================================================
ORIGINAL DATASET
============================================================

    ID   Name   Age       City  Marks
0  101   Amit  20.0  Ahmedabad   80.0
1  102  Rahul  21.0      Surat   90.0
2  103  Priya   NaN     Rajkot    NaN
3  104  Sneha  22.0  Ahmedabad   75.0
4  105   Amit  20.0  Ahmedabad   80.0
5  105   Amit  20.0  Ahmedabad   80.0
6  106   Neha  23.0   Vadodara   95.0
7  107   None  21.0     Rajkot   88.0
8  108  Karan   NaN      Surat   92.0
9  109   Riya  24.0       None   90.0

In [6]:
# ==========================================
# DATASET INFORMATION
# ==========================================

print("="*60)
print("DATASET INFORMATION")
print("="*60)

df.info()

print("\nShape :", df.shape)

print("\nColumns")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

============================================================
DATASET INFORMATION
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     int64
 1   Name    9 non-null      object
 2   Age     8 non-null      float64
 3   City    9 non-null      object
 4   Marks   9 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 532.0+ bytes

Shape : (10, 5)

Columns
['ID', 'Name', 'Age', 'City', 'Marks']

Data Types
ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

In [7]:
# ==========================================
# MISSING VALUES
# ==========================================

print("="*60)
print("MISSING VALUES")
print("="*60)

print(df.isnull().sum())

============================================================
MISSING VALUES
============================================================
ID       0
Name     1
Age      2
City     1
Marks    1
dtype: int64

In [8]:
# ==========================================
# DUPLICATE ROWS
# ==========================================

print("="*60)
print("DUPLICATE ROWS")
print("="*60)

duplicates = df[df.duplicated()]

display(duplicates)

print("Total Duplicate Rows :", df.duplicated().sum())

============================================================
DUPLICATE ROWS
============================================================

    ID  Name   Age       City  Marks
5  105  Amit  20.0  Ahmedabad   80.0

Total Duplicate Rows : 1

In [9]:
# ==========================================
# REPEATED VALUES
# ==========================================

print("="*60)
print("REPEATED NAMES")
print("="*60)

print(df["Name"].value_counts())

print()

print("="*60)
print("REPEATED CITIES")
print("="*60)

print(df["City"].value_counts())

============================================================
REPEATED NAMES
============================================================
Name
Amit     3
Rahul    1
Priya    1
Sneha    1
Neha     1
Karan    1
Riya     1
Name: count, dtype: int64

============================================================
REPEATED CITIES
============================================================
City
Ahmedabad    4
Surat        2
Rajkot       2
Vadodara     1
Name: count, dtype: int64

In [10]:
# ==========================================
# HANDLE MISSING VALUES
# ==========================================

df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df["Name"] = df["Name"].fillna("Unknown")

df["City"] = df["City"].fillna("Unknown")

print("="*60)
print("MISSING VALUES FILLED")
print("="*60)

display(df)

============================================================
MISSING VALUES FILLED
============================================================

    ID     Name     Age       City      Marks
0  101     Amit  20.000  Ahmedabad  80.000000
1  102    Rahul  21.000      Surat  90.000000
2  103    Priya  21.375     Rajkot  85.555556
3  104    Sneha  22.000  Ahmedabad  75.000000
4  105     Amit  20.000  Ahmedabad  80.000000
5  105     Amit  20.000  Ahmedabad  80.000000
6  106     Neha  23.000   Vadodara  95.000000
7  107  Unknown  21.000     Rajkot  88.000000
8  108    Karan  21.375      Surat  92.000000
9  109     Riya  24.000    Unknown  90.000000

In [11]:
# ==========================================
# REMOVE DUPLICATE ROWS
# ==========================================

df = df.drop_duplicates()

print("="*60)
print("DUPLICATE ROWS REMOVED")
print("="*60)

print("New Shape :", df.shape)

display(df)

============================================================
DUPLICATE ROWS REMOVED
============================================================
New Shape : (9, 5)

    ID     Name     Age       City      Marks
0  101     Amit  20.000  Ahmedabad  80.000000
1  102    Rahul  21.000      Surat  90.000000
2  103    Priya  21.375     Rajkot  85.555556
3  104    Sneha  22.000  Ahmedabad  75.000000
4  105     Amit  20.000  Ahmedabad  80.000000
6  106     Neha  23.000   Vadodara  95.000000
7  107  Unknown  21.000     Rajkot  88.000000
8  108    Karan  21.375      Surat  92.000000
9  109     Riya  24.000    Unknown  90.000000

In [12]:
# ==========================================
# REMOVE EXTRA SPACES
# ==========================================

df["Name"] = df["Name"].str.strip()

df["City"] = df["City"].str.strip()

print("="*60)
print("EXTRA SPACES REMOVED")
print("="*60)

============================================================
EXTRA SPACES REMOVED
============================================================

In [13]:
# ==========================================
# DATA TYPE CONVERSION
# ==========================================

df["Age"] = df["Age"].astype(float)

df["Marks"] = df["Marks"].astype(float)

print("="*60)
print("DATA TYPES AFTER CONVERSION")
print("="*60)

print(df.dtypes)

============================================================
DATA TYPES AFTER CONVERSION
============================================================
ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

In [14]:
# ==========================================
# DATA STATISTICS
# ==========================================

print("="*60)
print("DESCRIPTIVE STATISTICS")
print("="*60)

display(df.describe())

============================================================
DESCRIPTIVE STATISTICS
============================================================

               ID        Age      Marks
count    9.000000   9.000000   9.000000
mean   105.000000  21.527778  86.172840
std      2.738613   1.312169   6.575795
min    101.000000  20.000000  75.000000
25%    103.000000  21.000000  80.000000
50%    105.000000  21.375000  88.000000
75%    107.000000  22.000000  90.000000
max    109.000000  24.000000  95.000000

In [15]:
# ==========================================
# FINAL CLEAN DATASET
# ==========================================

print("="*60)
print("FINAL CLEAN DATASET")
print("="*60)

display(df)

============================================================
FINAL CLEAN DATASET
============================================================

    ID     Name     Age       City      Marks
0  101     Amit  20.000  Ahmedabad  80.000000
1  102    Rahul  21.000      Surat  90.000000
2  103    Priya  21.375     Rajkot  85.555556
3  104    Sneha  22.000  Ahmedabad  75.000000
4  105     Amit  20.000  Ahmedabad  80.000000
6  106     Neha  23.000   Vadodara  95.000000
7  107  Unknown  21.000     Rajkot  88.000000
8  108    Karan  21.375      Surat  92.000000
9  109     Riya  24.000    Unknown  90.000000

In [16]:
# ==========================================
# VERIFY CLEAN DATA
# ==========================================

print("="*60)
print("FINAL VERIFICATION")
print("="*60)

print("\nMissing Values")

print(df.isnull().sum())

print()

print("Duplicate Rows")

print(df.duplicated().sum())

print()

print("Shape")

print(df.shape)

print()

print("Columns")

print(df.columns.tolist())

print()

print("Data Types")

print(df.dtypes)

print()

print("="*60)
print("DATA CLEANING COMPLETED SUCCESSFULLY")
print("="*60)

============================================================
FINAL VERIFICATION
============================================================

Missing Values
ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

Duplicate Rows
0

Shape
(9, 5)

Columns
['ID', 'Name', 'Age', 'City', 'Marks']

Data Types
ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

============================================================
DATA CLEANING COMPLETED SUCCESSFULLY
============================================================